ok-stage: &ok_stage
  - name: git comment
    jobs:
      - name: make comment
        script: echo "looks good to me ðŸ‘" > comment.txt
      - name: submit comment
        type: git:comment
        options:
          fromFile: comment.txt

start-bert-server: &bert_stage
  - name: start bert service
    jobs:
      - name: bert-serving-start
        script: "bert-serving-start -model_dir ./chinese_L-12_H-768_A-12/ -mask_cls_sep -cpu &"
      - name: block 30s until server is ready
        script: sleep 30

install-deps: &install_deps
  - name: install dependencies
    jobs:
      - name: install project deps
        env:
          INDEX_URL: http://mirrors.oa.com/pypi/web/simple/
          TRUST_DOM: mirrors.oa.com
        script: "pip install -r requirements.txt -i ${INDEX_URL} --extra-index-url ${INDEX_URL} --trusted-host ${TRUST_DOM}"

basic-pipeline: &bp1
  docker:
    image: docker.oa.com:8080/public/ailab-py3-tf-bert:latest
  stages:
    - <<: *install_deps
    - name: check code style
      script: pylint src/**/*.py --exit-zero
    - name: check tensorflow works correctly
      script: "python -c 'import tensorflow as tf; print(tf.__version__); a=tf.constant(1, tf.int32); print(tf.Session().run(a))'"
    - <<: *bert_stage
    - name: run unit test
      script: python -m unittest tests/*.py
    - <<: *ok_stage


master:
  merge_request:
    - <<: *bp1
