!PipelineEncoder
components:
  - !BertEncoderWithServer
    components:
      bert_server:
        !BertEncoderServer
        parameters:
          args:
            - mask_cls_sep
          kwargs:
            port: 5555
            port_out: 5556
            model_dir: /ext_data/chinese_L-12_H-768_A-12
            max_seq_len: 40
            pooling_layer: -12
        gnes_config:
          is_trained: true
      bert_client:
        !BertEncoder
        parameters:
          kwargs:
            port: 5555
            port_out: 5556
            ignore_all_checks: true
        gnes_config:
          is_trained: true
  - !PCALocalEncoder
    parameters:
      output_dim: 300
      num_locals: 30
    gnes_config:
      batch_size: 2048
  - !PQEncoder
    parameters:
      cluster_per_byte: 100
      num_bytes: 30
