# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gnes_pb2 as gnes__pb2


class GnesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Index = channel.unary_unary(
        '/gnes.Gnes/Index',
        request_serializer=gnes__pb2.IndexRequest.SerializeToString,
        response_deserializer=gnes__pb2.IndexResponse.FromString,
        )
    self.Search = channel.unary_unary(
        '/gnes.Gnes/Search',
        request_serializer=gnes__pb2.SearchRequest.SerializeToString,
        response_deserializer=gnes__pb2.SearchResponse.FromString,
        )


class GnesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Index(self, request, context):
    """option (rpc_core.method_no_deadline) = true;
    option (rpc_core.service_default_deadline_ms) = 5000;
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GnesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Index': grpc.unary_unary_rpc_method_handler(
          servicer.Index,
          request_deserializer=gnes__pb2.IndexRequest.FromString,
          response_serializer=gnes__pb2.IndexResponse.SerializeToString,
      ),
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=gnes__pb2.SearchRequest.FromString,
          response_serializer=gnes__pb2.SearchResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gnes.Gnes', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
